---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: notes/index.md
  label: notes home
  match: "**/*"
- type: directory
  path: notes
  label: notes
  create: documents
  match: "**/*"
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
